# lib/language.py

LANG_DATA = {
    "en": {
        "title": "Particle Effect Toolkit",
        "opt1": "[1] Convert flexbuffers JSON to pure JSON (fix.py)",
        "opt2": "[2] Convert New to Old (old.py)",
        "opt3": "[3] Search Keys and SWF/SC references (search.py)",
        "opt4": "[4] Physical Merge/Append JSON (add.py)",
        "opt5": "[5] Switch Language",
        "opt6": "[6] Extract movieclip.swf SC names (sc_extract.py)",
        "opt7": "[7] Extract ParticleEmitterName matches from CSV (csv_name_extract.py)",
        "opt0": "[0] Exit",
        "input_choice": "Enter choice: ",
        "press_enter": "Press Enter to continue...",
        "src_file": "Input file",
        "out_file": "Output file",
        "success": "Success: Saved to",
        "error": "Error: File not found",
        "lang_select": "Select: 1. English | 2. 中文 | 3. Русский: ",
        "lang_title": "Select Language | 选择语言 | Выберите язык",
        "lang_prompt": ">>> ",
        "invalid_input": "Invalid input.",
        "runtime_error": "Error",
        "search_src_file": "Source file",
        "key_keyword": "Key keyword",
        "swf_keyword": "SC/SWF keyword",
        "base_file": "Base file",
        "patch_file": "Patch file",
        "sc_src_file": "Source file",
        "sc_out_file": "Output file",
        "csv_src_file": "CSV file",
        "name_json_src_file": "JSON file",
        "name_json_out_file": "Output file",
    },
    "zh": {
        "title": "粒子特效处理综合工具",
        "opt1": "[1] flexbuffers JSON 转纯 JSON (fix.py)",
        "opt2": "[2] 新版 JSON 转为旧版 (old.py)",
        "opt3": "[3] 搜索键值和 SWF 键的 SC 文件引用 (search.py)",
        "opt4": "[4] 物理合并拼接 JSON (add.py)",
        "opt5": "[5] 切换语言",
        "opt6": "[6] 提取 movieclip.swf 的 SC 名 (sc_extract.py)",
        "opt7": "[7] 从 CSV 提取 ParticleEmitterName 并导出键值 JSON (csv_name_extract.py)",
        "opt0": "[0] 退出",
        "input_choice": "请输入编号: ",
        "press_enter": "按回车键继续...",
        "src_file": "输入文件名",
        "out_file": "输出文件名",
        "success": "成功: 已保存至",
        "error": "错误: 找不到文件",
        "lang_select": "选择语言: 1. English | 2. 中文 | 3. Русский: ",
        "lang_title": "选择语言 | Select Language | Выберите язык",
        "lang_prompt": ">>> ",
        "invalid_input": "输入无效。",
        "runtime_error": "错误",
        "search_src_file": "搜索输入文件",
        "key_keyword": "键名关键词",
        "swf_keyword": "SC/SWF 关键词",
        "base_file": "基础文件",
        "patch_file": "补丁文件",
        "sc_src_file": "提取输入文件",
        "sc_out_file": "提取输出文件",
        "csv_src_file": "CSV 文件",
        "name_json_src_file": "搜索 JSON 文件",
        "name_json_out_file": "导出 JSON 文件",
    },
    "ru": {
        "title": "Инструментарий для эффектов",
        "opt1": "[1] Конвертировать flexbuffers JSON в чистый JSON (fix.py)",
        "opt2": "[2] Конвертировать Новый в Старый (old.py)",
        "opt3": "[3] Поиск ключей и ссылок на SC файлы (search.py)",
        "opt4": "[4] Физическое слияние JSON (add.py)",
        "opt5": "[5] Переключить язык",
        "opt6": "[6] Извлечь SC имена из movieclip.swf (sc_extract.py)",
        "opt7": "[7] Извлечь совпадения ParticleEmitterName из CSV (csv_name_extract.py)",
        "opt0": "[0] Выход",
        "input_choice": "Введите номер: ",
        "press_enter": "Нажмите Enter для продолжения...",
        "src_file": "Входной файл",
        "out_file": "Выходной файл",
        "success": "Успех: Сохранено в",
        "error": "Ошибка: Файл не найден",
        "lang_select": "Выбор языка: 1. English | 2. 中文 | 3. Русский: ",
        "lang_title": "Выберите язык | Select Language | 选择语言",
        "lang_prompt": ">>> ",
        "invalid_input": "Неверный ввод.",
        "runtime_error": "Ошибка",
        "search_src_file": "Файл для поиска",
        "key_keyword": "Ключевое слово ключа",
        "swf_keyword": "Ключевое слово SC/SWF",
        "base_file": "Базовый файл",
        "patch_file": "Файл патча",
        "sc_src_file": "Исходный файл",
        "sc_out_file": "Выходной файл",
        "csv_src_file": "CSV файл",
        "name_json_src_file": "JSON файл",
        "name_json_out_file": "Выходной JSON",
    }
}
